version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build tasks...
      - npm run lint
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the application...
      - npm run build
      - echo Running tests...
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging the application...
      - npm run package

artifacts:
  files:
    - '**/*'
  discard-paths: yes