AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for a Fargate-based proxy service with Network Load Balancer, streaming protocol support, and CloudWatch logging.

Metadata:
  Author: Maris Svirksts
  Version: 1.2
  Date: 2024-06-21

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC Id
    Default: vpc-0897a9f3de7e213c0 # growthos-discover-data-sandbox-vpc
  PublicSubnetOne:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Id for the first public subnet
    Default: subnet-01c1e6167c10cd939 # growthos-discover-data-sandbox-vpc GWDATAPublicSubnet1
  PublicSubnetTwo:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Id for the second public subnet
    Default: subnet-0ab49b33aca6b7531 # growthos-discover-data-sandbox-vpc GWDATAPublicSubnet2
  PrivateSubnetOne:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Id for the first private subnet
    Default: subnet-0698e2d7aa11f94ad # growthos-discover-data-sandbox-vpc GWDATAPrivateSubnet1
  PrivateSubnetTwo:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Id for the second private subnet
    Default: subnet-0dc656e9fbe33dc5c # growthos-discover-data-sandbox-vpc GWDATAPrivateSubnet2
  ApiEndpoint:
    Type: String
    Description: The API endpoint to forward requests to.
    Default: lgas1grdoai01.openai.azure.com
  Environment:
    Type: String
    Description: Environment tag for the resources
    Default: sandbox
  HealthCheckInterval:
    Type: Number
    Description: Interval for health checks in seconds, should not be larger than 300
    Default: 300
  ContainerImage:
    Type: String
    Description: Container image for the proxy service
    Default: nginx:latest
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for HTTPS (empty/ACM certificate ARN)
    Default: "arn:aws:acm:eu-west-1:155258020391:certificate/93583b08-9315-4458-a229-ef1c2ae0193b"
    AllowedPattern: "^$|arn:aws:acm:[^:]+:[0-9]{12}:certificate/.+"
    ConstraintDescription: Must be a valid ACM certificate ARN or an empty string.

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, ""]]

Resources:
  # IAM Role for ECS Task Execution
  TaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ecs/growthos-proxy-service:*"
      Tags:
        - Key: growthos:environment
          Value: !Ref Environment

  # CloudWatch Log Group
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/ecs/growthos-proxy-service
      RetentionInDays: 7
      Tags:
        - Key: growthos:environment
          Value: !Ref Environment

  # ECS Cluster
  Cluster:
    Type: 'AWS::ECS::Cluster'
    Properties: 
      ClusterName: growthos-discover-proxy-cluster
      Tags:
        - Key: growthos:environment
          Value: !Ref Environment

  # Network Load Balancer
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: growthos-discover-proxy-nlb
      Subnets:
        - !Ref PublicSubnetOne
        - !Ref PublicSubnetTwo
      Scheme: internet-facing
      Type: network
      Tags:
        - Key: growthos:environment
          Value: !Ref Environment

  # Target Group for HTTPS
  TargetGroupHttps:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: growthos-discover-proxy-https
      Port: 443
      Protocol: TCP
      VpcId: !Ref VpcId
      HealthCheckProtocol: TCP
      HealthCheckPort: '443'
      HealthCheckIntervalSeconds: !Ref HealthCheckInterval
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetType: ip
      Tags:
        - Key: growthos:environment
          Value: !Ref Environment

  # Load Balancer Listener for HTTPS with SSL Certificate
  ListenerHttps:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupHttps
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: TLS
      Certificates:
        - !If
          - HasCertificate
          - CertificateArn: !Ref CertificateArn
          - !Ref "AWS::NoValue"

  # Security Group
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTPS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: growthos:environment
          Value: !Ref Environment

  # ECS Task Definition
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: growthos-discover-proxy-task
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: proxy-container
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: 443
              Protocol: TCP
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /aws/ecs/growthos-proxy-service
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: proxy
          Environment:
            - Name: API_ENDPOINT
              Value: !Ref ApiEndpoint
          Command:
            - /bin/sh
            - -c
            - |
              cat <<EOF > /etc/nginx/nginx.conf
              worker_processes 1;
              error_log /dev/stderr warn;

              events { worker_connections 1024; }

              stream {
                  log_format main '\$ssl_preread_server_name \$remote_addr [\$time_local] "\$protocol" '
                                    '\$status \$bytes_sent "\$session_time" '
                                    '"\$upstream_addr" "\$upstream_bytes_sent" "\$upstream_connect_time"';
                  access_log /dev/stdout main;

                  upstream backend_https {
                      server ${API_ENDPOINT}:443;
                  }

                  server {
                      listen 443;
                      ssl_preread on;  # Enable SSL/TLS inspection
                      proxy_pass backend_https;
                  }
              }
              EOF
              nginx -g 'daemon off;'

  # ECS Service
  ProxyService:
    Type: 'AWS::ECS::Service'
    DependsOn: LoadBalancer
    Properties:
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      LoadBalancers:
        - ContainerName: proxy-container
          ContainerPort: 443
          TargetGroupArn: !Ref TargetGroupHttps
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PrivateSubnetOne
            - !Ref PrivateSubnetTwo
          SecurityGroups:
            - !Ref SecurityGroup
      Tags:
        - Key: growthos:environment
          Value: !Ref Environment

Outputs:
  LoadBalancerDnsName:
    Description: DNS name of the load balancer
    Value: !GetAtt LoadBalancer.DNSName

  ApiEndpoint:
    Description: The API endpoint the proxy forwards requests to
    Value: !Ref ApiEndpoint

  Environment:
    Description: The environment tag value
    Value: !Ref Environment

  HealthCheckInterval:
    Description: Interval for health checks in seconds
    Value: !Ref HealthCheckInterval
