Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx-proxy-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn:
        Fn::GetAtt:
          - ECSExecutionRole
          - Arn
      ContainerDefinitions:
        - Name: nginx-proxy
          Image:
            Fn::Join:
              - ''
              - - Ref: AWS::AccountId
                - .dkr.ecr.
                - ${self:provider.region}
                - .amazonaws.com/nginx-proxy:latest
          Essential: true
          PortMappings:
            - ContainerPort: 443
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/nginx-proxy
              awslogs-region: ${self:provider.region}
              awslogs-stream-prefix: nginx
          Environment:
            - Name: AZURE_SERVICE_URL
              Value: ${env:AZURE_SERVICE_URL}

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: ECSCluster
      DesiredCount: 1
      TaskDefinition:
        Ref: ECSTaskDefinition
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: nginx-proxy
          ContainerPort: 443
          TargetGroupArn:
            Ref: ALBTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Ref: PrivateSubnet1
            - Ref: PrivateSubnet2
          SecurityGroups:
            - Ref: SecurityGroup
