Resources:
  TaskLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/nginx-proxy
      RetentionInDays: 30

  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ECSHighCPUUtilization
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value:
            Ref: ECSCluster
        - Name: ServiceName
          Value:
            Ref: ECSService
      AlarmActions:
        - Ref: AlarmNotificationTopic

  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ECSAlarmNotificationTopic

  AlarmNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: ${env:ALARM_EMAIL}
      Protocol: email
      TopicArn:
        Ref: AlarmNotificationTopic
